### ISSUE TITLE
fix: update css class name

### ISSUE THREAD

**Issue by alexbarnsley** [cambo/cyj-theme_2#1]
https://github.com/cambo/cyj-theme_2/blob/e04620586ff242d438c0664a87af1836d2d5161c/src/styles/light.css#L1

The above line should be `.theme-plugin-cyj-theme {` to match the theme name from below as it is case sensitive

https://github.com/cambo/cyj-theme_2/blob/e04620586ff242d438c0664a87af1836d2d5161c/src/index.js#L4

**Comment by cambo** [comment]
Adjusted `index.js` to match `light.css` for the plugin name in index is what appears to user and want it capitalized. Thanks.
